# 1.4.4 Smoothing Images

## Kernel Convolution

In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [2]:
l=1
kernel = np.array([[0,-1,0],[-1,4,-1],[0,-1,0]],np.float32)

In [3]:
kernel

array([[ 0., -1.,  0.],
       [-1.,  4., -1.],
       [ 0., -1.,  0.]], dtype=float32)

In [4]:
img = np.random.randint(10, size=(12,12))
#img = np.ones((10,10),np.float32)

In [5]:
img

array([[8, 1, 7, 0, 2, 7, 1, 4, 3, 0, 0, 2],
       [5, 1, 9, 6, 1, 4, 2, 6, 2, 7, 5, 6],
       [8, 3, 9, 3, 3, 6, 5, 6, 5, 5, 1, 8],
       [5, 5, 9, 9, 9, 1, 9, 8, 0, 6, 9, 9],
       [4, 0, 0, 6, 1, 0, 4, 0, 5, 9, 9, 6],
       [7, 5, 8, 8, 5, 6, 9, 9, 7, 3, 7, 9],
       [0, 8, 5, 6, 4, 8, 2, 7, 0, 5, 0, 0],
       [4, 6, 9, 5, 2, 1, 1, 0, 2, 2, 1, 1],
       [1, 9, 1, 8, 7, 3, 2, 6, 6, 2, 5, 3],
       [4, 0, 1, 2, 8, 7, 0, 4, 9, 6, 1, 9],
       [0, 3, 1, 0, 1, 4, 3, 3, 6, 0, 8, 6],
       [7, 9, 6, 6, 8, 1, 0, 3, 1, 4, 1, 9]])

In [6]:
h,w=img.shape

In [7]:
print(h,w)

12 12


In [8]:
#[*range(-2,3)]

In [9]:
dst = np.zeros((h,w),int)

In [10]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i,j]=t        

In [11]:
img

array([[8, 1, 7, 0, 2, 7, 1, 4, 3, 0, 0, 2],
       [5, 1, 9, 6, 1, 4, 2, 6, 2, 7, 5, 6],
       [8, 3, 9, 3, 3, 6, 5, 6, 5, 5, 1, 8],
       [5, 5, 9, 9, 9, 1, 9, 8, 0, 6, 9, 9],
       [4, 0, 0, 6, 1, 0, 4, 0, 5, 9, 9, 6],
       [7, 5, 8, 8, 5, 6, 9, 9, 7, 3, 7, 9],
       [0, 8, 5, 6, 4, 8, 2, 7, 0, 5, 0, 0],
       [4, 6, 9, 5, 2, 1, 1, 0, 2, 2, 1, 1],
       [1, 9, 1, 8, 7, 3, 2, 6, 6, 2, 5, 3],
       [4, 0, 1, 2, 8, 7, 0, 4, 9, 6, 1, 9],
       [0, 3, 1, 0, 1, 4, 3, 3, 6, 0, 8, 6],
       [7, 9, 6, 6, 8, 1, 0, 3, 1, 4, 1, 9]])

In [12]:
dst

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0, -14,  13,  11, -11,   0,  -8,  10, -13,  16,   6,   0],
       [  0, -11,  12, -15,  -7,  11,  -3,   0,   7,   1, -23,   0],
       [  0,   3,  13,   9,  22, -20,  18,  17, -24,   1,  11,   0],
       [  0, -14, -23,   6, -16, -12,  -2, -26,   4,  13,   5,   0],
       [  0,  -3,  14,   7,   1,   2,  15,  13,  11, -16,   7,   0],
       [  0,  16, -11,   2,  -5,  19, -17,  17, -21,  15, -13,   0],
       [  0,  -6,  19,  -5,  -9, -10,  -1, -16,   0,  -2,  -4,   0],
       [  0,  28, -23,  17,   7,  -5,  -2,  12,   5, -11,  13,   0],
       [  0, -17,   0,  -9,  15,  13, -16,  -2,  14,  12, -24,   0],
       [  0,   2,  -6, -10, -16,   4,   5,  -4,  11, -24,  24,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [13]:
img = cv2.imread('lena.png', 0)

In [14]:
h,w=img.shape

In [15]:
dst = np.zeros((h-2*l,w-2*l),np.uint8)

In [16]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i-l,j-l]=t 

In [17]:
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()