# 1.4.4 Smoothing Images

## Kernel Convolution

In [1]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [2]:
l=1
kernel = np.array([[0,-1,0],[-1,4,-1],[0,-1,0]],np.float32)

In [3]:
kernel

array([[ 0., -1.,  0.],
       [-1.,  4., -1.],
       [ 0., -1.,  0.]], dtype=float32)

In [35]:
img = np.random.randint(10, size=(12,12))
#img = np.ones((10,10),np.float32)

In [36]:
img

array([[3, 6, 0, 6, 4, 3, 5, 9, 7, 9, 3, 6],
       [3, 8, 7, 0, 8, 1, 0, 7, 2, 2, 0, 2],
       [3, 7, 6, 3, 6, 5, 4, 5, 1, 0, 8, 5],
       [4, 5, 3, 3, 2, 4, 3, 9, 4, 7, 8, 4],
       [9, 7, 6, 7, 0, 4, 7, 3, 3, 2, 6, 3],
       [6, 0, 7, 2, 1, 5, 6, 1, 5, 8, 5, 3],
       [6, 6, 1, 1, 0, 6, 8, 5, 6, 8, 3, 6],
       [0, 2, 6, 5, 2, 4, 5, 9, 4, 7, 5, 7],
       [8, 3, 7, 5, 8, 9, 2, 1, 8, 3, 3, 4],
       [6, 6, 6, 3, 1, 7, 0, 3, 3, 7, 8, 7],
       [2, 2, 5, 5, 8, 7, 1, 5, 9, 4, 3, 7],
       [5, 7, 9, 7, 7, 6, 9, 6, 1, 2, 0, 0]])

In [37]:
h,w=img.shape

In [38]:
print(h,w)

12 12


In [16]:
#[*range(-2,3)]

In [39]:
dst = np.zeros((h,w),int)

In [40]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i,j]=t        

In [41]:
img

array([[3, 6, 0, 6, 4, 3, 5, 9, 7, 9, 3, 6],
       [3, 8, 7, 0, 8, 1, 0, 7, 2, 2, 0, 2],
       [3, 7, 6, 3, 6, 5, 4, 5, 1, 0, 8, 5],
       [4, 5, 3, 3, 2, 4, 3, 9, 4, 7, 8, 4],
       [9, 7, 6, 7, 0, 4, 7, 3, 3, 2, 6, 3],
       [6, 0, 7, 2, 1, 5, 6, 1, 5, 8, 5, 3],
       [6, 6, 1, 1, 0, 6, 8, 5, 6, 8, 3, 6],
       [0, 2, 6, 5, 2, 4, 5, 9, 4, 7, 5, 7],
       [8, 3, 7, 5, 8, 9, 2, 1, 8, 3, 3, 4],
       [6, 6, 6, 3, 1, 7, 0, 3, 3, 7, 8, 7],
       [2, 2, 5, 5, 8, 7, 1, 5, 9, 4, 3, 7],
       [5, 7, 9, 7, 7, 6, 9, 6, 1, 2, 0, 0]])

In [42]:
dst

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
       [  0,   9,  14, -24,  21, -12, -17,  12,  -9,  -3, -15,   0],
       [  0,   6,   4,  -3,   6,   5,   3,  -1,  -7, -18,  19,   0],
       [  0,  -1,  -8,  -3,  -5,   2, -12,  21,  -4,  14,   7,   0],
       [  0,   8,   0,  17, -14,   0,  12,  -8,  -2, -16,   6,   0],
       [  0, -26,  19,  -8,  -3,   3,   3, -15,   2,  12,   0,   0],
       [  0,  15, -16,  -4, -10,   7,  10,  -4,   2,   8, -12,   0],
       [  0,  -7,   9,   6,  -9,  -6,  -3,  21, -14,   8,   0,   0],
       [  0, -11,   8,  -3,  15,  15,  -7, -18,  21, -13,  -8,   0],
       [  0,   7,   3,  -5, -22,  11, -13,   3, -15,  10,  12,   0],
       [  0, -12,  -2,  -3,  12,   6, -17,   1,  23,  -5,  -7,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0]])

In [5]:
img = cv2.imread('lena.png', 0)

In [6]:
h,w=img.shape

In [7]:
dst = np.zeros((h-2*l,w-2*l),np.uint8)

In [8]:
for i in range(l,h-l):
    for j in range(l,w-l):
        t=0
        for p in range(-l,l+1):
            for q in range(-l,l+1):
                t += kernel[p+l,q+l]*img[i+p,j+q]
        dst[i-l,j-l]=t 

In [9]:
cv2.imshow('img',img)
cv2.imshow('dst',dst)
cv2.waitKey(0)
cv2.destroyAllWindows()